# Generated by Django 4.0.4 on 2022-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
